### ISSUE TITLE
[Bug]: Hourglass icon added behind every widget starting v1.18

### ISSUE THREAD

**Issue by Veazer** [fibelatti/photo-widget#124]
### Describe the problem

I just noticed this problem (Nov 8, 2024) so I believe it is connected to the v1.18 release as I have never seen it before. I use many partially opaque .png files on my desktop and I now have an hourglass icon on each:

![material-photo-widget-issue](https://github.com/user-attachments/assets/ba573d83-e4fa-402d-a13b-cd07413a36a8)

I'm guessing this is a loading icon that has been moved to the background layer when not in use? It's not visible on opaque images but it does create problems with transparency as shown. 

### Device model

Google Pixel 4 XL

### Android version

Android 13 [GrapheneOS]

### App version

1.18

**Comment by fibelatti** [comment]
Hi @Veazer, this issue has been fixed in version 1.18.1. The update is already available on Google Play Store and GitHub, and should become available on IzzyOnDroid later today

**Comment by Veazer** [comment]
This problem came back, but the icon is different. I made a change to the configuration and resaved it and this caused the icon to go away, but I assume it is never meant to be visible. 

![Image](https://github.com/user-attachments/assets/d61a6bce-7413-40a0-bbe3-ba28ad9fc80d)

**Comment by fibelatti** [comment]
@Veazer that icon indicates that the current photo failed to load for some reason. I'll investigate to see if there's an underlying issue, thanks for bringing it to my attention.
